security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_provider:
            id: App\Security\Provider\UserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api
            provider: app_provider
            stateless: true
            custom_authenticators:
                - App\Security\Authenticator\AccessTokenAuthenticator
        main:
            pattern: ^/(?!api)
            provider: app_provider
            form_login:
                login_path: app_login
                check_path: app_login
                use_referer: true
            logout:
                path: /logout
    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/token, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
